training:
  batch_size: 4 #128
  n_epochs: 500000
  n_iters: 210001
  snapshot_freq: 5000 #5000
  snapshot_sampling: true
  anneal_power: 2
  log_all_sigmas: false

sampling:
  batch_size: 64
  data_init: false
  step_lr: 0.0000033
  n_steps_each: 5
  ckpt_id: 210000
  final_only: true
  fid: false
  denoise: true
  num_samples4fid: 10000
  inpainting: false
  interpolation: false
  n_interpolations: 15

fast_fid:
  batch_size: 1000
  num_samples: 1000
  step_lr: 0.0000033
  n_steps_each: 5
  begin_ckpt: 5000
  end_ckpt: 210000
  verbose: false
  ensemble: false

test:
  begin_ckpt: 5000
  end_ckpt: 210000
  batch_size: 100

data:
  dataset: "marmousi_unet"
  image_size: 128
  channels: 1
  logit_transform: false
  uniform_dequantization: false
  gaussian_dequantization: false
  random_flip: true
  rescaled: false
  seis_rescaled: true
  num_workers: 0 #32
  image_shape: (128,128)

model:
  sigma_begin: 90
  num_classes: 500
  ema: true
  ema_rate: 0.999
  spec_norm: false
  sigma_dist: geometric
  sigma_end: 0.01 # 0.01
  normalization: InstanceNorm++
  nonlinearity: elu
  ngf: 128
  depth: 4
  wf: 64
  slope: 0.2

optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.0001
  beta1: 0.9
  amsgrad: false
  eps: 0.00000001
